rusty patcher
dzshn/Quartet pull request #3
Opened 2023-02-09 01:56 UTC by dzshn

:transgender_flag:

2023-02-09 22:51 UTC, Vendicated commented
unrust immediately

2023-02-10 13:02 UTC, fawni requested changes

2023-02-10 13:02 UTC, fawni commented on qpatcher/src/main.rs
> +            for p in quartet_path.ancestors().collect::<Vec<_>>().iter().rev() {
```suggestion
            for p in quartet_path.ancestors().into_iter().rev() {
```
NOW

2023-02-10 15:00 UTC, Vap0r1ze commented on qpatcher/src/main.rs
> +            for p in quartet_path.ancestors().collect::<Vec<_>>().iter().rev() {
byee fishyyyy

2023-02-10 16:23 UTC, fawni commented on qpatcher/src/main.rs
> +            for p in quartet_path.ancestors().collect::<Vec<_>>().iter().rev() {
fishy stays

2023-02-12 18:07 UTC, Vap0r1ze approved these changes
im so tired but i think its epic maybe group the functions by target in `path.rs` tho

2023-02-12 23:12 UTC, merged